[tool.cibuildwheel]
before-all = [
  "cd third_party/nvxs-1.0.2",
  "./configure",
  "make",
  "case \"$(uname -s)\" in Darwin) sudo make install;; *) make install;; esac",
]

[tool.yapf]
based_on_style = "pep8"
